### ISSUE TITLE
Usability improvements proposal

### ISSUE THREAD

**Issue by vsopko** [mrlacey/VSHighlighter#3] opened 2024-11-24 14:56 UTC
1. Add editable keyboard shortcuts to quik set/remove highlights. For example Ctrl+1 - fuchsia Ctrl+2 - gold, etc.
2. Add context menu option to remove signle highlight from document (where cursor is), not all.
3. Add mark on the vertical scroll bar for quik navigation. May be it is better to draw it is as a horizontal line with appropriate color, to not confuse with many dots that may be shown by VS itself.
4. Editable colors

**Comment by mrlacey** [comment] 2024-11-25 10:56
Hi @vsopko Thanks for the feedback. I wasn't expecting anyone to use this yet and so I know there are a bunch of opportunities for improvement. Thanks for taking the time to make these suggestions.

> 1. Add editable keyboard shortcuts to quik set/remove highlights. For example Ctrl+1 - fuchsia Ctrl+2 - gold, etc.

You should be able to do this yourself.
Go to Tools > Options > Keyboard, then search for commands starting "HighlightSelection" and then you can assign the shortcut you wish.
Whenever I've tried to provide default shortcuts, someone always complains that they conflict with other workloads or extensions they have installed.
When a shortcut is assigned to multiple things, VS does nothing and it's hard to identify what the issue is. 

> 2. Add context menu option to remove signle highlight from document (where cursor is), not all.

If you right-click on circle in the margin it will remove that highlight.
Adding a context menu to remove an individual highlight has scenarios where it's not clear which highlight to remove. I'll add this to the backlog though.

> 3. Add mark on the vertical scroll bar for quik navigation. May be it is better to draw it is as a horizontal line with appropriate color, to not confuse with many dots that may be shown by VS itself.

Will investigate.

> 4. Editable colors

Is more work than I want to consider right now.

**Comment by mrlacey** [comment] 2024-11-25 12:22
> > 3. Add mark on the vertical scroll bar for quik navigation. May be it is better to draw it is as a horizontal line with appropriate color, to not confuse with many dots that may be shown by VS itself.
> 
> Will investigate.

There doesn't seem to be an API that enables adding to the annotations that VS shows in the scroll bar :(

**Comment by vsopko** [comment] 2024-11-25 16:02
> There doesn't seem to be an API that enables adding to the annotations that VS shows in the scroll bar :(

Here is an attempt to draw on VS scrollbar in similar type of extension:
https://github.com/oleg-shilo/PyMap.VSIX/commit/a2389fcd3024cd2240f3cacc7e2e8baeefba17ad

**Comment by mrlacey** [comment] 2024-12-02 14:09
> > There doesn't seem to be an API that enables adding to the annotations that VS shows in the scroll bar :(
> 
> Here is an attempt to draw on VS scrollbar in similar type of extension: [oleg-shilo/PyMap.VSIX@a2389fc](https://github.com/oleg-shilo/PyMap.VSIX/commit/a2389fcd3024cd2240f3cacc7e2e8baeefba17ad)

Thanks for that, it helped me find a solution that is in v1.4

**Closed as completed by mrlacey** 2024-12-02 14:09 UTC
